# Generated by Django 2.1.2 on 2018-10-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicenseModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license_description',
            name='conditions',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='license_description',
            name='limitations',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='license_description',
            name='permissions',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='license_description',
            name='synopsis',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='license_description',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
