# Generated by Django 2.1.2 on 2018-10-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicenseModel', '0002_auto_20181020_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('meaning', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='limitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('meaning', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('meaning', models.TextField(null=True)),
            ],
        ),
    ]
