# Generated by Django 2.1.2 on 2018-11-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicenseModel', '0003_condition_limitation_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='license_description',
            name='csv_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='license_description',
            name='text_key',
            field=models.TextField(null=True),
        ),
    ]
